### PR TITLE
Add optional callback to FollowRedirects

### PR DESCRIPTION
**Pull request by lislis**
We at Travis CI are great fans of Faraday. We use it all over the place, thank you so much 🎉 

We would like to respond to redirects, eg logging the event. 

This change adds an optional callback to FollowRedirects.

### CODE REVIEW

**Comment by svenfuchs** [comment]
It seems the specs have been failing on Travis CI for quite a while. We've looked through these, and it seems all these are due to dependency incompatibilities that have been introduce over time.

Would you like us to help fixing the test dependencies in order for this PR to be accepted?

**Comment by iMacTia** [comment]
Hi @lislis and @svenfuchs, thanks for your contribution!

We're aware of those issues and @sbleon has very recently made a great work of fixing all those dependency issues. Since I'm talking about recent changes I suppose your branch was created before that fix. Can you please double-check if there's any commit you can pull from master?

Apologies also for the slow replies but I'm currently abroad till the end of next week.
I really hope we can have this merged soon 😊

**Comment by svenfuchs** [comment]
Thanks @iMacTia!

We've created the fork on Friday, implemented the change, and pushed it. We'll have a look if we've missed any upstream changes during that time.

**Comment by svenfuchs** [comment]
@iMacTia the last change on `master` is from Sep 30, 2015. The only other branch is `0.9`, last commit from Jul 8, 2015.

I don't think there's anything we could pull in.

**Comment by iMacTia** [comment]
My fault, I completely confused faraday main gem with Faraday middleware gem!
The change @sbleon did recently was on the main gem!
I'm quite confident we simply need to apply the same fixes on this repository, but unfortunately I won't have a computer till I'm back 🙁

@sbleon, if you have some time can you see if you can apply the same fixes here?
@svenfuchs, if @sbleon is busy and you fill comfortable, you can try to fix test on a separate PR 😊, or just wait for me to come back next week.

**Comment by iMacTia** [comment]
Commit I'm referring to above: https://github.com/lostisland/faraday/commit/a712938071bb0997410b5de4a4f2517d30fc4d3d

**Comment by svenfuchs** [comment]
@iMacTia I see. I'm not sure how you suggest we'd pull that in though. `faraday-middleware` is tested against released gem versions, not the `master` branch, as far as I can tell. Also, lots of this seems to be referring to the test setup, which would need to be ported to `faraday-middleware`. Are you suggesting we'd manually port these fixes to the test setup? I'm probably misunderstanding what you have in mind.

**Comment by iMacTia** [comment]
No you're definitely right!
I didn't have a chance to look at tests yet so I didn't know they simply included Faraday latest released version, even though it makes sense.
At this point, I think the best thing to do is to wait the release of v0.10 which should be imminent and use that to run tests (simply changing version constraints in gemspec). That version will include all changes from @sbleon to fix dependent gems versions.

@sbleon should release it in the next days, otherwise it will be one of the first thing I'll do as soon as I'm back next week. I'm sorry to make you waiting

**Comment by mislav** [comment]
I've just pushed dependency fixes to master that make it green again in CI.

**Comment by svenfuchs** [comment]
@iMacTia gotcha, makes sense

@mislav w00t! thank you so much!

I've rebased our changes and it looks like we've got some fixing to do with Ruby < 2.x https://travis-ci.org/lostisland/faraday_middleware/builds/159853828

We'll look at this asap. Thanks a lot for your help.

**Comment by lislis** [comment]
Hey there @mislav @iMacTia we fixed the issues we had in the older Ruby versions and squashed. 
Is this good to be merged? Thanks in advance!

**Comment by iMacTia** [comment]
Reviewed and good to go for me.
It looks like a good addition to the middleware.
Thanks @lislis and @svenfuchs!
Merging

**Comment by svenfuchs** [comment]
Super, thanks a lot @iMacTia!

Any chance we can get a release for this? ❤️

**Comment by iMacTia** [comment]
I'm currently abroad so not sure if @sbleon will make 0.10 release before I'm back but it's definitely in the short term plan :)!
There are other changes we would like to release asap so can't promise but hopefully next week you'll see something ;)

**Comment by mislav** [comment]
Could anyone take a look at #118 and decide whether this feature supersedes that?

**Pull request merged**
