### PR TITLE
Use full URL (url.host + url.request_uri) as cache key

### PR DESCRIPTION
**Pull request by vmanivchuk**

### CODE REVIEW

**Comment by olleolleolle** [comment]
The "full key" form disambiguates, which is better. 

(Keeping the old form around for compatibility - is it necessary, in your opinion? I think it may not be necessary.)

@technoweenie How did this work before? Did site_a.com/path and site-b.com/path return the _same_ cached content? (That's my understanding from this diff.) If yes, then let's apply this immediately.

**Comment by vmanivchuk** [comment]
Keeping the old form for compatibility is necessary because there can be issue with key length. And yes, site_a.com/path and site-b.com/path return the same cached content.

**Comment by olleolleolle** [comment]
Would it be acceptable to switch over to this new behavior in an upcoming major version?

**Comment by vmanivchuk** [comment]
Yes, of course.

**Comment by iMacTia** [comment]
Wanted to include this in last 0.1x release as it's a pretty good point!

**Pull request merged**
