### PR TITLE
Middleware for XML encoder (second try)

### PR DESCRIPTION
**Pull request by AlexWayfer**
Recreation of ignored #126 (thanks to @abookyun)

### CODE REVIEW

**Comment by iMacTia** [comment]
Hi @AlexWayfer, thanks for resurrecting this issue! Lots of things have changed over the last years (I can see that's a pretty old ticket!) and we're now not adding any new middleware to faraday_middleware anymore.
On the contrary, we're planning on moving them into their own gems.

I'd suggest you to go down that route as well. You'll be able to maintain that gem without having to rely on the faraday team!

We've recently setup a [template repository](https://github.com/lostisland/faraday-middleware-template) to make creating new middleware really simple. Please do give it a try!

**Comment by AlexWayfer** [comment]
@iMacTia OK, thank you for detailed response. I can understand such reasonable approach. I'll try, I guess.

Would you move some third-party gems into `lostisland` organization or list links to them somewhere?

**Comment by iMacTia** [comment]
Ah yes good point! I forgot to mention selve also setup a [discovery repo](https://github.com/lostisland/awesome-faraday) ❤️
Feel free to open a PR there to add your new middleware, it looks interesting!

As for creating the repos inside the lost island organisation, we'd only do that for gems we want to actively maintain, but I don't think that would apply in this case.

You'll be one of the first outside the core team to setup such a gem, so feel free to reach out if you encounter any issue, we'll be happy to help and it will allow us to collect feedback and improve the template repo for future uses 👍

**Comment by AlexWayfer** [comment]
> We've recently setup a [template repository](https://github.com/lostisland/faraday-middleware-template) to make creating new middleware really simple. Please do give it a try!

FYI, it seems that templates work only for owners (org members):



I just don't see such button, as well as others like `Create file`.

(I didn't know should I wrote here about this or create an issue there, but I don't think that this is a repo issue and I didn't find "Discussions" section in template repo)

**Comment by AlexWayfer** [comment]
> Ah yes good point! I forgot to mention selve also setup a [discovery repo](https://github.com/lostisland/awesome-faraday) 
> Feel free to open a PR there to add your new middleware, it looks interesting!

Thanks.



> As for creating the repos inside the lost island organisation, we'd only do that for gems we want to actively maintain, but I don't think that would apply in this case.

Got it.

> You'll be one of the first outside the core team to setup such a gem, so feel free to reach out if you encounter any issue, we'll be happy to help and it will allow us to collect feedback and improve the template repo for future uses

Thank you for your kind words.

**Comment by iMacTia** [comment]
> FYI, it seems that templates work only for owners (org members)

It was not setup as a template 🤦, my fault! Try again now, it should show the button

**Comment by AlexWayfer** [comment]
Oh, now I see such button!



Thank you.

**Comment by olleolleolle** [comment]
I'd like to take the opportunity to say 🎉 WELCOME 🎉  and thanks for discovering all those small inconvenient things that could be improved. You have smoothed the ground for the next pioneer!

**Pull request closed without merging**
