### PR TITLE
Don't register the request/response json middleware for Faraday 1.10+

### PR DESCRIPTION
**Pull request by iMacTia**
## Summary

Faraday 1.10 ships with an out-of-the-box JSON middleware, so we want to to default to that one rather than the faraday_middleware one.
See [this comment](https://github.com/lostisland/faraday/issues/1594#issuecomment-2363834919) for more details.

### CODE REVIEW

**Comment by olleolleolle** [comment]
It looks like the change is sound, but the CI needs a little love.

```
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.6.10.210.
```

**Comment by iMacTia** [comment]
I've updated the CI workflow, hopefully it will work now.
If not, I'll take a look later 🙂

**Comment by olleolleolle** [comment]
@iMacTia I pushed changes to get to green, this branch can now be resolved.

**Comment by olleolleolle** [comment]
I will resolve the conflict in this PR right now.

**Comment by olleolleolle** [comment]
I got excited and extracted the https://github.com/lostisland/faraday_middleware/pull/291 as well, to keep the edits in this change as focused as we can.

**Review by olleolleolle — APPROVED** [review]
🚀

**Comment by WvanLelyveld** [comment]
This PR seems to break things for us after all.
We have
```
> Gem::Version.new(Faraday::VERSION)
#<Gem::Version "1.10.4">
```
and upgrading faraday_middleware from 1.2.0 to 1.2.1 breaks all tests that do some kind of JSON importing.
Seems like the JSON middleware is not loaded correctly somehow.
Am I doing something wrong here?

**Comment by iMacTia** [comment]
@WvanLelyveld do you have an error or, even better, a stacktrace to share?

**Comment by WvanLelyveld** [comment]
@iMacTia I've made [a test repo with two branches](https://github.com/WvanLelyveld/faraday-middleware-testcase).
You can see the only difference is the version of faraday_middleware, v1.2.0 and v.1.2.1
In the main branch, v1.2.1, rspec fails, where in the working-with-1.2.0 branch, the rspec test passes.

This should illustrate that this version breaks things in certain case.
I'm suspecting it has something to do with the absence of the response_headers in the mocked response.
The original `ParseJson` class in faraday_middleware parses this response, even in the absence of headers, where the now used Faraday::Response::Json does not when there are no headers.

**Pull request merged**
