### PR TITLE
Add token_type option for specifying method of adding OAuth2 tokens

### PR DESCRIPTION
**Pull request by cjford**
As discussed in #130.

Still missing updated documentation - I'm not sure what the procedure is for editing the wiki or the timeline for doing it against releasing changes. Let me know if you have a preferred way of handling that.

### CODE REVIEW

**Comment by iMacTia** [comment]
@cjford thanks for your PR!

I would really like to get this fixed, however I noticed something strange.
I understood from #130 that the token was only added to the url, but having a closer look to the code I found it being added in the Authorization header as well, even though the format is not the standard one.

So unfortunately I need to ask you to slightly change this PR to give full backward-compatibility, even though the implementation is poor.

Thanks

**Comment by iMacTia** [comment]
@cjford Hold on, please answer to my last comment in #130 before changing this PR

**Comment by cjford** [comment]
@iMacTia No problem - I've updated the commit to continue adding the "Token token=" Authorization header by default as it did originally. Let me know if you have any more feedback.

**Comment by iMacTia** [comment]
Great work @cjford 👍 !

This adds a better implementation of an existing feature without breaking backward-compatibility.
Merging

**Pull request merged**
