### PR TITLE
Fix compatibility with Faraday 1.0

### PR DESCRIPTION
**Pull request by yuki24**
This PR adds a build matrix for Faraday 1.0 and fixes the failing specs.

### CODE REVIEW

**Comment by zenspider** [comment]
This broke inspec/inspec as well. We aliased the old namespacing over to the new namespacing as a workaround. It's just a 1-liner and might be easier to swallow than this PR:

https://github.com/inspec/inspec/pull/4531/commits/984e02e312d004c2dd8318a44b7562a49e4d0687

We'd really like SOME fix to be upstream from us tho. This will start to affect more and more and Gemfiles get bumped in CIs. Especially confusing since it was faraday that bumped, not faraday_middleware.

**Comment by glaszig** [comment]
would somebody please merge/fix and release? thank you.

**Comment by bastelfreak** [comment]
Hi people. Since faraday 1.0 is out, could one of the maintainers have a look here?

**Comment by oshow** [comment]
Why spec are failing:
In faraday 1.0, this `env[:body]` refers to request_body, because status has not yet been set here.
https://github.com/lostisland/faraday_middleware/blob/be685418ba8ef4c428f726e7b943b2fb64860ec5/spec/unit/follow_redirects_spec.rb#L52

**Comment by iMacTia** [comment]
I'm close this in favour of #196 which goes for a different approach: FaradayMiddleware v1.0 will be compatible with Faraday 1.0 (I'll try to make it compatible with Faraday 0.17.x as well, but that remains to be seen

**Pull request closed without merging**
