### PR TITLE
Remove Addressable::URI query hack

### PR DESCRIPTION
**Pull request by sdogruyol**
This has caused a really hard leaky spec for us while working with [Restforce](https://github.com/restforce/restforce) and [Addressable](https://github.com/sporkmonger/addressable).

We explicitly use the `cache` function of `Restforce` which relies on `FaradayMiddleware::Caching` and actually that breaks `Addressable::URI` query params ordering because of https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/addressable_patch.rb

That's why I propose to remove this monkey patch indefinitely :+1:

### CODE REVIEW

**Comment by iMacTia** [comment]
@sdogruyol I had a quick look at why Mislav introduced this patch and it looks like the reason is that `Addressable::URI` can't compare different paths unless the query params are in the correct order.
With this patch, params order won't affect the comparison and I agree with Mislav this should be the correct behaviour as the params order doesn't really matter in HTTP calls.

As you can see, removing the patch breaks our tests because of that, so I can't possibly merge this PR.
Moreover, I'd be interested to know how this is causing issues for you?

**Comment by iMacTia** [comment]
@sdogruyol for the time being, I'd suggest changing [this line](https://github.com/lostisland/faraday_middleware/blob/master/.travis.yml#L4) to `before_install: gem install bundler -v '<2'`

**Comment by sdogruyol** [comment]
Updated and specs are :heavy_check_mark:

**Comment by sdogruyol** [comment]
Thank you @iMacTia :+1:

**Pull request merged**
